image: golang:1.15

variables:
  REPO: gitlab.com/MrGunflame/gw2api

before_script:
  - mkdir -p /src/$(dirname $REPO)
  - ln -svf $CI_PROJECT_DIR /src/$REPO
  - cd $GOPATH/src/$REPO_NAME

stages:
  - test

test:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)
